version: '3'

services:

        app:
           build: docker
           container_name: app-blog
           user: root
           volumes:
              - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
           ports:
             - "${APACHE_HOST_HTTP_PORT}:80"

        database:
           image: postgres
           ports:
              - "${DBPORT}:${DBPORT}"
           environment:
              - "POSTGRES_DB=${DBNAME}"
              - "POSTGRES_USER=${DBUSER}"
              - "POSTGRES_PASSWORD=${DBPASS}"           
        composer:
           image: composer
           volumes:
              - .:/app

        adminer:
           image: adminer
           ports:
              - 8080:8080