version: '3'

services:

        app:
           build: docker
           container_name: app
           user: root
           volumes:
              - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
           ports:
             - "${APACHE_HOST_HTTP_PORT}:80"

        database:
           container_name: database
           image: postgres
           env_file:
              - .env

        adminer:
           container_name: adminer
           image: adminer
           ports:
              - 8080:8080